toml.py
dictionary can sometimes contain keys with a None value. This leads to the generation of a TOML string with None in it. This is not valid TOML.
=> Remove None values when dumping Mapping

toml.py
Trivial dict like this would fail to parse.
```toml
test = {x = -3}
```
=> Added minus sign to allow negative numbers in inline dicts

toml.py
[The spec says](https://github.com/toml-lang/toml#spec):
> A TOML file must be a valid UTF-8 encoded Unicode document.
Builtin `open()` in Python 3 uses `locale.getpreferredencoding(False)` by default. It may differ from utf-8. To read a TOML file, the utf-8 encoding should be passed explicitly.
=> always read toml file using utf-8

toml.py
As promised in #86, I've split this uncontroversial change into it's own pull request.
=> Do not override dict __init__ for InlineTableDict

toml.py
Refactored the _dump method to lookup corresponding method based on the values current type. Prevents repeated type checks on a single variable.
Also replaced use of `_range(len(sl))` with `enumerate` to iterate over the list `sl` storing the current value in `item` and index in `i`. This prevent repeated lookups of `sl` with `sl[i]`.
Everything seems to work okay on my end after running and comparing the output with that of the master branch using:
`python toml_test.py < examples/example-v0.4.0.toml`
It could be the case that the PR completely crashes and burns when running the tests properly. Let me konw if that's the case as I might need some guidance running them correctly.
Cheers, Jack
=> Refactor _dump method and replaced range(len) with enumerate

setup.py, toml.py
Sometimes it can be useful to reference what version of `toml` one is using, especially as the spec continues to change.
```python
>>> import toml
>>> print(toml.__version__)
'0.9.2'
```
=> Enable support for toml.__version__

toml.py
As long as there's at least _one_ existing file in the list given.
To permit things like the examples listed here: https://github.com/uiri/toml/issues/9#issuecomment-17939193
Hopefully the result becomes either what's in `config.ini` or `config_dev.ini` if either's opposite is non-existent on the filesystem.
=> Feature: Let load() handle non-existing files in list.

toml.py
Currently, a value like `10.0` will be dumped out as `10`, whereas it should be dumped out as `10.0`.
From the [python docs](https://docs.python.org/3.4/library/string.html#format-specification-mini-language), dropping the `g` in the format string yields the following behaviour:
```
Similar to 'g', except that fixed-point notation, when used, has at least one digit past the decimal point. The default precision is as high as needed to represent the particular value. The overall effect is to match the output of str() as altered by the other format modifiers.
```
=> floats like 10.0 should remain floats when dumped

toml/decoder.py
I made the `TomlDecodeError` more like the `JSONDecodeError` from the stdlib json module, allowing position information to be surfaced in errors.
This partially addresses https://github.com/uiri/toml/issues/100, as line numbers are reported accurately in errors. However, column numbers are harder to track in the current code; as a result, errors will often say "column 1", when the issue occurred elsewhere in the line. Also, errors in multiline arrays report the opening line, because they are currently in-lined before parsing.
=> Fix #100: track position while parsing for better errors

tests/test_api.py, toml/__init__.py, toml/decoder.py, toml/encoder.py, toml/ordered.py
Firstly, I am sorry that git's diff algorithm can't understand the changes in this PR for the life of it. Even in split mode, it looks far messier than it actually is. See #135 for context around splitting up the module into a package of modules (i.e. what the hell happened in the base that this PR is `diff`'d against).
So the 0.9.X Toml API is something like:
`dumps(o, preserve=False)`
`loads(s, _dict=dict)`
The new Toml API I'm proposing is something like:
`dumps(o, decoder=None)`
`loads(s, encoder=None)`
Given a `None` encoder or decoder, the method creates one from the default `TomlEncoder` or `TomlDecoder` class. Examples of custom Encoders are: `TomlArraySeparatorEncoder`, `TomlPreserveInlineDictEncoder`, and the `TomlOrderedEncoder`. An example of a custom Decoder is …
=> New API: Encoder / Decoder model

setup.cfg
Hi there!
Since this package is a pure Python package, I believe the wheels it produces should be compatible with both Python 2 and Python 3.
By marking it as producing universal wheels, it will produce one wheel instead of two. This makes it a tiny bit easier for people to upload wheels to their internal PyPI registries, plus improves cache performance in pip if you're using `toml` from both Python 2 and Python 3.
More details about universal wheels: https://wheel.readthedocs.io/en/stable/#defining-the-python-version
```bash
$ python setup.py bdist_wheel
$ ls dist
toml-0.10.0-py2-none-any.whl
```
```bash
$ python setup.py bdist_wheel
$ ls dist
toml-0.10.0-py2.py3-none-any.whl
```
=> Produce a universal wheel

toml/decoder.py
Now this works
```
> import toml
> a="var = 0x100"
> toml.loads(a)
{u'var': 256}
```
As well as this:
```
> import toml
> a = """
... hex = 0xAB03
... binary = 0b100101
... octal = 0o630
... """
> toml.loads(a)
{u'octal': 408, u'binary': 37, u'hex': 43779}
```
acording to [0.5.0 spec](https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.5.0.md#user-content-integer)
> Non-negative integer values may also be expressed in hexadecimal, octal, or binary.
=> Add support for hexadecimal, octal and binary numbers

examples/example-v0.4.0.toml, toml/decoder.py
Adds support for Local Dates, which are in the spec on `toml-lang/toml/master` but not in the official 4.0 spec release. 
```toml
ldt1 = 1979-05-27T07:32:00
ldt2 = 1979-05-27T00:32:00.999999
ldt3 = 1979-05-27
```
Becomes
```python
In [3]: toml.load(f)
Out[3]:
{'ldt1': datetime.datetime(1979, 5, 27, 7, 32),
'ldt2': datetime.datetime(1979, 5, 27, 0, 32, 0, 999999),
'ldt3': datetime.date(1979, 5, 27)}
```
=> Added support for Local Dates

setup.py
The trove classifiers are listed on PyPI to help users know -- at a
glance -- what license the project uses. Helps users decide if the
library is appropriate for integration. A full list of available trove
classifiers can be found at:
https://pypi.org/pypi?%3Aaction=list_classifiers
The setuptools "license" argument is not intended to use trove
classifier notation. Simplify it to "MIT". Details can be found:
https://docs.python.org/3/distutils/setupscript.html#additional-meta-data
=> Add trove classifier for license

toml/encoder.py
Due to the fact that `TomlArraySeparatorEncoder` (and `TomlPreserveInlineDictEncoder`) call `super` using `self.__class__` if you inherit from one of those classes a recursion error is encountered.
```
Traceback (most recent call last):
File "/Users/matt/projects/ansibledev/ansible/bin/ansible-inventory", line 118, in <module>
exit_code = cli.run()
File "/Users/matt/projects/ansibledev/ansible/lib/ansible/cli/inventory.py", line 185, in run
results = self.dump(results)
File "/Users/matt/projects/ansibledev/ansible/lib/ansible/cli/inventory.py", line 209, in dump
results = toml.dumps(stuff, encoder=AnsibleTomlEncoder())
File "/Users/matt/projects/ansibledev/ansible/lib/ansible/plugins/inventory/toml.py", line 110, in __init__
super(AnsibleTomlEncoder, self).__init__(*args, **kwargs)
File …
```
=> Call to super should use explicit class

MANIFEST.in
Don't need to specify `setup.py` as it is included automatically by `setuptools`.
Don't need to include package Python files (`toml/*`) as they're included automatically by `setuptools`.
Alphabetized list.
Fixes #192
=> Include tests in source distribution; clean up MANIFEST.in

toml/decoder.py
- Detects escaping for quotes to avoid prematurely parsing a quoted key as closed
- Unescapes characters in a quoted key.
=> Fix 206: Bug relating to escaped quotes in quoted keys

toml/decoder.py
I got the following warning with `Python 3.7` + `toml 0.10.0`
toml/decoder.py:47: DeprecationWarning: invalid escape sequence \.
TIME_RE = re.compile("([0-9]{2}):([0-9]{2}):([0-9]{2})(\.([0-9]{3,6}))?")
This warning could be avoidable by using raw string.
=> Fix a deprecation warning

.flake8, tests/test_api.py, toml/encoder.py
If an object is passed to dumps, and that object has a circular
reference, then dumps will raise a ValueError because an object with
circular references cannot be encoded as valid TOML.
=> Fix #217: dumps unable to detect circular refs

tests/test_api.py
Hello,
This is a little sanitization fix to prevent resource leaks.
=> Fix ResourceWarning: unclosed file in test_api.py

tests/test_api.py, toml/encoder.py
In `toml 0.9.6`, `decimal.Decimal` values are converted into strings as follows:
```py
import toml
from decimal import Decimal
d = {"a": Decimal("0.1")}
print(toml.dumps(d))
```
```
a = "Decimal('0.1')"
```
It would be helpful if `toml.dumps` method output `float` values when input value types are `decimal.Decimal`:
```
a = 0.1
```
=> Add support for decimal.Decimal encoding

tests/test_api.py, toml/decoder.py
This PR aims to fix ambv/black#637
The issue can be reproduce as follows (`Python 3.7` with `toml 0.10.0`):
```pycon
>>> import toml
>>> toml.loads(r"""
... [tool.poetry.dev-dependencies]
... black = { python=">3.6", version=">=18.9b0", allow_prereleases=true }
... """)
Traceback (most recent call last):
File "/home/.../site-packages/toml/decoder.py", line 456, in loads
multibackslash)
File "/home/.../site-packages/toml/decoder.py", line 725, in load_line
value, vtype = self.load_value(pair[1], strictly_valid)
File "/home/.../site-packages/toml/decoder.py", line 805, in load_value
self.load_inline_object(v, inline_object)
File "/home/.../site-packages/toml/decoder.py", line 624, in load_inline_object
multibackslash)
File "/home/.../site-packages/toml/decoder.py", line 678, in load_line …
```
=> Fix loading values when a line has " }" after a boolean

toml/decoder.py
Fixes https://github.com/uiri/toml/issues/234 .
=> When calling load() with an array of filenames, use the requested dictionary type.

toml/encoder.py
Precision in a python format string, without a type specifier, formats
the content as a _string_, where the precision indicates the maximum
field size. This results in numbers with a large integer part, but a
small decimal part, being truncated unnecessarily. eg.
>>> '{0:.16}'.format(1555609276.1339364)
'1555609276.133936'
=> Remove precision from dump float

.vscode/settings.json, README.rst, toml/__init__.py, toml/encoder.py
This pull request does two things:
1. In `toml.dump` allows passing an encoder argument. Currently, to use a non-standard encoder users are forced to use `toml.dumps` followed by file-writing themselves. `toml.dump` should include the encoder argument to avoid this.
2. Updated README documentation to show the new arguments and gives an example of using the `TomlNumpyEncoder`. I fell into quite the rut in my code because my numpy arrays were saving as strings. The only way I figured out how to solve it was finding an old closed issue and then trying to figure out the usage through reading the source code. Hopefully adding this documentation will help users moving forward.
I have also incremented to version to `0.10.1` in hopes that a release (or pre-release) will be made on PyPI so I can …
=> Small documentation and argument update

tests/test_api.py, toml/encoder.py
I have extend TomlNumpyEncoder to handle numpy integer types. I've also added the unit test for these cases.
=> Extend TomlNumpyEncoder to numpy integer types.

toml/decoder.py
Fix a bug where a key without a value does not cause an error when it
is not followed by a newline at the end of a file.
=> Fix #258: Fix bad syntax handling

.travis.yml, setup.py, tox.ini
Also simplify `.travis.yml` a bit because [`sudo` no longer has any effect](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration) and because Xenial is now the default.
=> Add support for Python 3.8

tests/test_api.py, toml/decoder.py
Given a TOML file with an unterminated string value as the last option in the file
```toml
opt='''
this is a test
of an unfinished string
```
Current toml version (0.10.0) will simply not load that option instead of raising an Exception. The following test code returns an empty dict given the above toml file
```python
import toml
import pathlib
filepath = pathlib.Path('test.toml')
data = toml.loads(filepath.read_text())
assert bool(data)
```
=> Raise an exception if EOF is reached and a string is unterminated

README.rst
Great, simple, and intuitive library! Would have saved me a decent amount of time though if there was an example provided for **toml.dump**.
=> added toml.dump example to Quick Tutorial

tests/test_api.py, toml/tz.py
Without this method, the dict that results from parsing a datetime with a timezone cannot be deep-copied using the stdlib `copy.deepcopy()` function.
Example:
```python
import copy
import toml
o = toml.loads("dob = 1979-05-27T07:32:00-08:00")
copy.deepcopy(o)
```
This currently raises a `TypeError`.
=> Fix #308: Add __deepcopy__ method to the `tz.TomlTz` class

toml/decoder.py
according to the spec booleans are all lowercase, when a capitalized boolean is used, the error message is not very informative ("This float doesn't have a leading digit")
=> show meaningful error message for wrong case booleans

.travis.yml, setup.py, tox.ini
All tests pass for Python 3.9 without modifications to the source code. This commit adjusts the classifiers in `setup.py` and adds Python 3.9 to the tox and CI test environments.
=> Add official support for Python 3.9

toml/tz.py
Related to #407
In previous version, combining toml and pickle do not work. We can pickle them, but it cannot be loaded becauseTomlTz objects were not able to be pickled.
I made TomlTz picklable.
Procedure to reproduce the previous problem:
1. prepare a toml file including a datetime value with timezone
2. load the toml file by `toml.load()`
3. (do some editing)
4. update the toml file by `toml.dump()` and save as pickle
5. the toml file can be opened, but the pickled file could not be opened.
=> Support pickle for TomlTz. Fix #407

toml/encoder.py
The current implementation of `TomlEncoder` doesn't support subtypes of the supported basic types. For example:
```py
from enum import StrEnum
import toml
class ValidStrings(StrEnum):
FOO = "foo"
assert isinstance(ValidStrings.FOO, str) # OK
data = {"foo": ValidStrings.FOO}
print(toml.dumps(data))
```
Output:
```
foo = [ "f", "o", "o",]
```
This pull request changes the implementation to use `isinstance` instead of `get(type(...))` to play nice with inheritence.
Fixes #418
=> Support subtypes of basic types when encoding

.gitignore, tests/test_api.py, toml/decoder.py, toml/encoder.py
+ add parenthesis in encoder.py, because without them py3.10 did not want to run the code:
```
Generator expressions must be parenthesized if not sole argument
```
=> Fix #430: list index out of range

tests/test_api.py
Tests in toml-test have been moved into subdirectories (https://github.com/BurntSushi/toml-test/pull/80). Current unit tests ([test_valid_tests](https://github.com/uiri/toml/blob/5706d3155f4da8f3b84875f80bfe0dfc6565f61f/tests/test_api.py#L47), [test_invalid_tests](https://github.com/uiri/toml/blob/5706d3155f4da8f3b84875f80bfe0dfc6565f61f/tests/test_api.py#L163)) are unable to pick up toml files in subdirectories. 
This PR change will allow the unit tests to traverse the whole directory tree (`toml-test/tests/valid/` and `toml-test/tests/invalid/`), including sub directories.
=> Iterate over all files in toml-test/tests, including sub dirs

toml/decoder.py
This should be case-insensitive; e.g. this test failed:
% toml-test ./tests/decoding_test.py -run valid/datetime/datetime
FAIL valid/datetime/datetime
Key "lower" is not "datetime" but "datetime-local":
Expected:     map[string]any{"type":"datetime", "value":"1987-07-05T17:45:00Z"}
Your encoder: map[string]any{"type":"datetime-local", "value":"1987-07-05T17:45:00"}
=> Treat "Z" offset in datetime as case-insensitive
